Module4/testing/books/urls.py
from django.urls import path
from django.views.generic import ListView
from books.models import Book, Author
from books.views import books_list, book_details, authors_list, author_details, borrows_list

app_name = "books"

urlpatterns = [
   path('', books_list, name="list"),
   path('<int:id>', book_details, name="details"),
   path('authors', authors_list, name="authors"),
   path('authors/<int:id>', author_details, name="author"),
   path('borrows', borrows_list, name="borrows"),

]

Module4/testing/posts/urls.py
from django.urls import path
from django.views.generic import ListView
from posts.models import Post
from posts.views import posts_list, post_details, authors_list, author_details

app_name = "posts"

urlpatterns = [
   path('', posts_list, name="list"),
   path('<int:id>', post_details, name="details"),
   path('authors', authors_list, name="authors"),
   path('authors/<int:id>', author_details, name="author"),
   path('list', ListView.as_view(model=Post), name="posts_list")
]

Module4/testing/testing/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .api import posts_router, books_router

urlpatterns = [
    path('', include("infos.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('maths/', include("maths.urls")),
    path('greetings/', include("greetings.urls")),
    path('posts/', include("posts.urls")),
    path('books/', include("books.urls")),
    path('api/v1/', include(posts_router.urls)),
    path('api/v2/', include(books_router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Module4/testing/posts/models.py
from django.db import models

class Post(models.Model):
   title = models.CharField(max_length=20)
   content = models.TextField()
   created = models.DateTimeField(auto_now_add=True)
   modified = models.DateTimeField(auto_now_add=True)
   author_id = models.ForeignKey('posts.Author', on_delete=models.CASCADE, null=True, blank=True)
   image = models.ImageField(upload_to='photos/%Y/%m/%d')
   tags = models.ManyToManyField("posts.Tag", related_name="posts")

   def __str__(self):
        return f"id:{self.id}, title={self.title}, author_id={self.author_id.nick}"


class Author(models.Model):
   nick = models.CharField(max_length=5)
   email = models.EmailField()

   def __str__(self):
        return f"id:{self.id}, nick={self.nick}, email={self.email}"


class Tag(models.Model):
   word = models.CharField(max_length=50, unique=True)
   created = models.DateTimeField(auto_now_add=True)

Module4/testing/posts/forms.py
from django import forms
from .models import Author, Post


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"

class PostForm(forms.ModelForm):
   class Meta:
       model = Post
       fields = "__all__"
       fields = ["title", "content", "author_id", "image", "tags"]

Module4/testing/posts/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages

from posts.models import Post, Author
from posts.forms import AuthorForm, PostForm

def index(request):
    c = {"title": "Welcome to blog posts app."}
    return render(
        request=request,
        template_name="posts/home.html",
        context=c
    )


def posts_list(request):
   posts = Post.objects.all()
   form = PostForm()
   if request.method == "POST":
       form = PostForm(data=request.POST, files=request.FILES)
       if form.is_valid():
           form.save()
           messages.add_message(
               request,
               messages.SUCCESS,
               "New post added"
           )

   return render(
       request=request,
       template_name="posts/posts_list.html",
       context={"posts": posts, "form": form}
   )


def post_details(request, id):
   post = Post.objects.get(id=id)
   return render(
       request=request,
       template_name="posts/post_details.html",
       context={"post": post}
   )


def authors_list(request):
   authors = Author.objects.all()
   form = AuthorForm()

   if request.method == "POST":
       form = AuthorForm(data=request.POST)
       if form.is_valid():
           form.save()
           messages.add_message(
               request,
               messages.SUCCESS,
               "New author added"
           )

   return render(
       request=request,
       template_name="posts/authors_list.html",
       context={"authors": authors, "form": form}
   )


def author_details(request, id):
   author = Author.objects.get(id=id)
   return render(
       request=request,
       template_name="posts/author_details.html",
       context={"author": author}
   )

Module4/testing/posts/templates/posts/author_details.html
{% extends "main.html" %}

{% block title %}Author detail{% endblock %}

{% block content %}
   <table>
       <tr>
           <th>Nick</th>
           <td>{{ author.nick }}</td>
       </tr>
       <tr>
           <th>E-Mail</th>
           <td>{{ author.email }}</td>
       </tr>
   </table>
   <br/>
   <a href="{% url "posts:authors_list" %}">back</a>
{% endblock %}

Module4/testing/posts/templates/posts/authors_list.html
{% extends "main.html" %}

{% block title %}Authors list{% endblock %}

{% block content %}
   <ul>
       {% for a in authors %}
           <li><a href="{% url "posts:author_details" a.id %}">{{ a }}</a></li>
       {% endfor %}
   </ul>

   <br/>
   New Author:
   <form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="go">
    </form>
{% endblock %}

Module4/testing/posts/templates/posts/home.html
{% extends "main.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<ul>
  <li><a href="/posts/p/">Posts</a></li>
  <li><a href="/posts/a/">Authors</a></li>
</ul>
{% endblock %}

Module4/testing/posts/templates/posts/post_details.html
{% extends "main.html" %}

{% block title %}Post detail{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<h2>{{ post.author.nick }} | {{ post.created }}</h2>
<p>
   {{ post.content }}
</p>
<div><img src="{{ post.image.url }}"></div>

<br/>
<a href="{% url "posts:posts_list" %}">back</a>
{% endblock %}

Module4/testing/posts/templates/posts/post_list.html
{% extends "main.html" %}

{% block title %}Posty{% endblock %}

{% load django_bootstrap5 %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
   {{ block.super }}
   {% breadcrumb "posts" "posts:list" %}
{% endblock %}

{% block content %}
   {% render_breadcrumbs %}
   <div class="row">
       <div class="col-6">
           <table class="table">
           <tr>
               <th>Tytuł</th>
               <th>Autor</th>
               <th>Data</th>
           </tr>
               {% for p in post_list %}
                   <tr>
                       <td><a href="{% url "posts:details" p.id %}">{{ p.title }}</a></td>
                       <td>{{ p.author.nick }}</td>
                       <td>{{ p.created }}</td>
                   </tr>
               {% endfor %}
           </table>
       </div>
       <div class="col-6">
       </div>
   </div>

{% if perms.posts.add_post %}
  <h2>New Post</h2>
  <form method="POST" enctype='multipart/form-data'>
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" value="Add">
    </form>
{% endif %}


{% endblock %}

Module4/testing/posts/templates/posts/posts_list.html
{% extends "main.html" %}
{% load django_bootstrap5 %}

{% block title %}Posts list{% endblock %}

{% block content %}
   <ul>
       {% for p in posts %}
           <li><a href="{% url "posts:details" p.id %}">{{ p }}</a></li>
       {% endfor %}
   </ul>
   <br/>

{% if perms.posts.add_post %}
  <h2>New Post</h2>
  <form method="POST" enctype='multipart/form-data'>
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" value="Add">
    </form>
{% endif %}


{% endblock %}