Module4/testing/books/urls.py
from django.urls import path
from django.views.generic import ListView
from books.models import Book, Author
from books.views import books_list, book_details, authors_list, author_details, borrows_list

app_name = "books"

urlpatterns = [
   path('', books_list, name="list"),
   path('<int:id>', book_details, name="details"),
   path('authors', authors_list, name="authors"),
   path('authors/<int:id>', author_details, name="author"),
   path('borrows', borrows_list, name="borrows"),

]

Module4/testing/testing/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .api import posts_router, books_router

urlpatterns = [
    path('', include("infos.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('maths/', include("maths.urls")),
    path('greetings/', include("greetings.urls")),
    path('posts/', include("posts.urls")),
    path('books/', include("books.urls")),
    path('api/v1/', include(posts_router.urls)),
    path('api/v2/', include(books_router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Module4/testing/books/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Book(models.Model):
   title = models.CharField(max_length=20)
   author_id = models.ForeignKey('books.Author', on_delete=models.CASCADE, null=True, blank=True)
   image = models.ImageField(upload_to='photos/%Y/%m/%d')
   tags = models.ManyToManyField("books.Tag", related_name="books")
   created = models.DateTimeField(auto_now_add=True)

   def __str__(self):
        return f"id:{self.id}, title={self.title}, author_id={self.author_id.name}, tags={self.tags}"


class Author(models.Model):
   name = models.CharField(max_length=20)
   created = models.DateTimeField(auto_now_add=True)

   def __str__(self):
        return f"id:{self.id}, name={self.name}"


class Tag(models.Model):
   word = models.CharField(max_length=50, unique=True)
   created = models.DateTimeField(auto_now_add=True)

   def __str__(self):
        return f"id:{self.id}, title={self.word}"


class Borrow(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
   book_id = models.ForeignKey('books.Book', on_delete=models.CASCADE, null=True, blank=True)
   borrowed = models.DateTimeField(auto_now_add=True)
   returned = models.DateTimeField(null=True, blank=True)
   is_returned = models.BooleanField(default=False)

   def __str__(self):
        return f"id:{self.id}, user={self.user}, book_id={self.book_id}, is_returned={self.is_returned}"

Module4/testing/books/forms.py
from django import forms
from .models import Borrow


class BorrowForm(forms.ModelForm):
    class Meta:
        model = Borrow
        fields = "__all__"

Module4/testing/books/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages
from django.core.paginator import Paginator

from books.models import Book, Author, Borrow

from datetime import datetime


def books_list(request):
   books = Book.objects.all()

   paginator = Paginator(books, 3)
   page_number = request.GET.get('page')
   books = paginator.get_page(page_number)

   return render(
       request=request,
       template_name="books/books_list.html",
       context={"books": books}
   )


def book_details(request, id):
   book = Book.objects.get(id=id)
   borrows = Borrow.objects.filter(book_id=book)

   if request.method == "POST":
       user = request.user
       Borrow.objects.create(user=user, book_id=book)


   borrowable = True
   if borrows:
       for b in borrows:
           if not b.is_returned:
               borrowable = False

   return render(
       request=request,
       template_name="books/book_details.html",
       context={"book": book, "borrowable": borrowable}
   )


def authors_list(request):
   authors = Author.objects.all()
   return render(
       request=request,
       template_name="books/authors_list.html",
       context={"authors": authors}
   )


def author_details(request, id):
   author = Author.objects.get(id=id)
   author_books = Book.objects.filter(author_id=author.id)
   return render(
       request=request,
       template_name="books/author_details.html",
       context={"author": author, "author_books": author_books}
   )


def borrows_list(request):
   if request.method == 'POST' and 'borrow_id' in request.POST:
       borrow = Borrow.objects.get(id=request.POST['borrow_id'])
       borrow.is_returned = True
       borrow.returned = datetime.now()
       borrow.save()


   borrows = Borrow.objects.filter(is_returned=False)
   return render(
       request=request,
       template_name="books/borrows_list.html",
       context={"borrows": borrows}
   )

Module4/testing/books/templates/books/author_details.html
{% extends "main.html" %}

{% block title %}Author detail{% endblock %}

{% block content %}
   <table>
       <tr>
           <th>Name</th>
           <td>{{ author.name }}</td>
       </tr>
       <tr>
           <th>Books</th>
           <td>
            <ul>
                {% for b in author_books %}
                    <li><a href="{% url "books:details" b.id %}">{{ b.title }}</a></li>
                {% endfor %}
            </ul>
           </td>
       </tr>
   </table>
   <br/>
   <a href="{% url "books:authors" %}">back</a>
{% endblock %}

Module4/testing/books/templates/books/authors_list.html
{% extends "main.html" %}

{% block title %}Authors list{% endblock %}

{% block content %}
   <ul>
       {% for a in authors %}
           <li><a href="{% url "books:author" a.id %}">{{ a.name }}</a></li>
       {% endfor %}
   </ul>

   <br/>
{% endblock %}

Module4/testing/books/templates/books/book_details.html
{% extends "main.html" %}

{% block title %}Book detail{% endblock %}

{% block content %}
<h1>{{ book.title }}</h1>
<h2><a href="{% url "books:author" book.author_id.id %}">{{ book.author_id.name }}</a></h2>
<h3>{{ book.created }}</h3>
<br/>

<div><img src="{{ book.image.url }}"></div>
<br/>

{% if borrowable %}
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Borrow">
</form>
{% endif %}

<a href="{% url "books:list" %}">back</a>
{% endblock %}

Module4/testing/books/templates/books/books_list.html
{% extends "main.html" %}
{% load django_bootstrap5 %}

{% block title %}Books list{% endblock %}

{% block content %}
   <ul>
       {% for b in books %}
           <li><a href="{% url "books:details" b.id %}">{{ b.title }}</a></li>
       {% endfor %}
   </ul>

   <br/>
   <div class="pagination">
    <span class="step-links">
        {% if books.has_previous %}
            <a href="?page=1">« first</a>
            <a href="?page={{ books.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ books.number }} of {{ books.paginator.num_pages }}.
        </span>

        {% if books.has_next %}
            <a href="?page={{ books.next_page_number }}">next</a>
            <a href="?page={{ books.paginator.num_pages }}">last »</a>
        {% endif %}
    </span>
    </div>

    <br/>
    <a href="{% url "books:authors" %}">Authors list</a>
    <br/>
    <a href="{% url "books:borrows" %}">Borrows list</a>

{% endblock %}

Module4/testing/books/templates/books/borrows_list.html
{% extends "main.html" %}

{% block title %}Borrows list{% endblock %}

{% block content %}
   <ul>
       {% for b in borrows %}
           <li>
            {{ b.book_id.title }}
            <form method="POST" class="float-right">{% csrf_token %}
            <input type="hidden" name="borrow_id" value="{{ b.id }}">
            <button class="btn btn-success">Return</button></form>
           </li>
       {% endfor %}
   </ul>

   <br/>
{% endblock %}